Import('env')
import gslab_scons as gs

build  = env['CONFIG']['global']['build']['load_data']
data   = env['CONFIG']['global']['input']['load_data']
remote = env['CONFIG']['user']['input']['remote']
base   = Dir('#.').path

gs.build_anything(target  = ['#%s/data.txt' % (build)],
			      source  = [''],
			      action  = 'rclone copy %s:%s/data.txt %s/%s' % (remote, data, base, build),
                  log_ext = 'load_data',
                  env     = env)

env.Install('#release/lg', '#%s/' % build)