Import('env')
import gslab_scons as gs

build  = env['CONFIG']['global']['build']['load_data']
data   = env['CONFIG']['user']['input']['load_data']
base   = Dir('#.').path

gs.build_anything(target  = ['#%s/data.txt'                     % (build)],
			      source  = [''],
			      action  = 'rclone copy %s/data.txt %s/%s'  % (data, base, build),
                  log_ext = 'load_data',
                  env     = env)

env.Install('#release/lg', '#%s/' % build)